AWSTemplateFormatVersion: '2010-09-09'
Description: Front-end deployment for Fund Management System

Resources:
  # s3
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: frontend-fund-management
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  # lambda
  FrontendLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FrontendLambda
      Handler: index.handler
      Runtime: nodejs14.x
      Code:
        S3Bucket: !Ref s3-amaris
        S3Key: !Ref # aqui va la llave del .zip
      Role: !GetAtt LambdaExecutionRole.Arn

  # cloud front
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendBucket.WebsiteURL
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Enabled: true
        DefaultRootObject: index.html

  # lambda rtoles
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::frontend-fund-management/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  # acceso cloudfront
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access to S3 frontend bucket

Parameters:
  CodeS3Bucket:
    Type: String
    Description: The S3 bucket where the Lambda code is stored

  CodeS3Key:
    Type: String
    Description: The S3 key for the Lambda code zip file